path = "/Users/mbailey/work/deprec/lib/"
# path = ''
require "#{path}deprec/recipes/deprec"
require "#{path}deprec/recipes/users"
require "#{path}deprec/recipes/deprecated"
require "#{path}deprec/recipes/canonical"
require "#{path}deprec/recipes/ssh"
require "#{path}deprec/recipes/apache"
require "#{path}deprec/recipes/nginx"
require "#{path}deprec/recipes/mongrel"
require "#{path}deprec/recipes/mysql"
require "#{path}deprec/recipes/php"
# require "#{path}deprec/recipes/subversion.rb"
# require "#{path}deprec/recipes/trac.rb"
require "#{path}deprec/third_party/vmbuilder/plugins"
require "#{path}deprec/capistrano_extensions/deprec_extensions"